---
title: "Expected Loss Model"
author: "Jiaxin Li (edited by Jayanth)"
date: "May 29, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
library(RODBC)
library(Hmisc)
library(ISLR)
library(sqldf)
library(doBy)
library(ggplot2)
library(rmarkdown)
library(dplyr)
library(gmodels)
library(xgboost)
library(gbm)
library(pROC)
library(ineq)
library(scorecard)
library(dummies)
library(data.table)
library(Matrix)
library(pdp)
library(caret)
library(haven)
library(grid)
library(tictoc)
```

Data Pull
```{r}

combined<- read_sas("Z:\\SAS Data\\user\\jvontela\\Data\\com_compliant_attributes_1516s.sas7bdat")
#com_ol17<- read_sas("Z:\\SAS Data\\user\\jvontela\\Data\\com_ol17.sas7bdat")


```

User-defined Functions

```{r}

cap.floor<-function(data){
  x=ifelse(data<=quantile(data, c(.01),na.rm = T),quantile(data, c(.01),na.rm = T),ifelse(data>=quantile(data, c(.99),na.rm = T),quantile(data, c(.99),na.rm = T),data))

}


data_fun<-function(x){
  
  rmvars=c("LOAN_ORG_DATE","MONTH_END_DATE","DEALNBR","MODEL_SCORE","BALANCE_AS_OF_3_22_19","FEE","DEAL_DT","MIGRATEDDEALNBR","SSN","MONTHENDDT",
         "CUSTNBR","TRACK_ID","FD_REQUEST_DTTM","FI_EEE_IN_REQUEST_ID","LOAN_REQUEST_DTTM","LOAN_REQUEST_ID","COMPANY_FIRSTDT","PRODUCT_FIRSTDT",
         "DEF_DT","PD","PRE_LOAN_DEAL_DT_LAST","DOB","DEAL_SNAP_DIFFERENCE","HOUSING_STATUS","LOAN_APP_HOUSING_STATUS",
         #remove that don't make sense
         "MODEL_TYPE","LOAN_SNAP_DELINQ_DAYS","AA_CMOB_SNAP","GROSSPAYPERCHECK","CUST_TOTAL_DELINQ_DAYS_IN_180","CUST_DAYS_IN_DELINQ_STATUS180",
         "DEALNUM_OPEN_IN_60","PDL_DEALNUM_OPEN_IN_120","PDL_DEALNUM_OPEN_IN_180","INA_MIN","INA_TOTAL","CUST_DAYS_IN_DELINQ_STATUS60","CUST_TOTAL_DELINQ_DAYS_IN_60",
         "GROSS_INCOME_AMT","PROD_CMOB_SNAP","CUST_DAYS_IN_DELINQ_STATUS120","CUST_TOTAL_DELINQ_DAYS_IN_365","CUST_DAYS_IN_DELINQ_STATUS365","CUST_TOTAL_DELINQ_DAYS_IN_90",
         "CUST_TOTAL_DELINQ_DAYS_IN_120","CUST_POSIT_DELINQ_DAYS_IN_365","CHANNELCD"
         )
  x=select(x,-one_of(rmvars))
  
  x$random=runif(nrow(x),0,1)
  x$LGDrandom=ifelse(x$LGD>x$random,1,0)
  x$LGDmean=ifelse(x$LGD>mean(x$LGD),1,0)
  
  x_var=select(x,-c("LGD","LGDmean","LGDrandom"))
  x_num=select_if(x_var,is.numeric)
  x_num1=apply(x_num,2,cap.floor)
  x_left=select(x,-one_of(colnames(x_num1)))
  x_final=cbind(x_left,x_num1)

  dummy.data.frame(data.table(x_final), names=names(x_final)[which(lapply(x_final,class)%in%c("character","factor"))], sep=".",verbose=T)

}

#com_ol17DUM <- data_fun(com_ol17)
combinedDUM <- data_fun(combined)
trainDUM=split_df(combinedDUM,ratio=.7,seed=123)[[1]]
testDUM=split_df(combinedDUM,ratio=.7,seed=123)[[2]]
rm(combined)

```

Parameters
Model
Evaluation Log
```{r}
tic("Model")
parms=list(max_depth = 5,eta = .02, nthread = 6,subsample = 0.5,colsample_bytree = 1,seed = 1,min_child_weight=100
           ,early.stop.rounds=30,objective = "binary:logistic",print_every_n= 500)

dropvars=c("LGD","LGDmean","LGDrandom")

bst <- xgboost(data = as.matrix(select(trainDUM,-one_of(dropvars))),label=as.matrix(select(trainDUM,LGDrandom)), params=parms#,monotone_contstraints=monotonicity
               ,eval_metric="auc",nrounds = 1500,verbose=1,nfold=2,maximize=F)

save(bst, file = "Z:/SAS Data/user/jvontela/Projects/20.IFRS9 MODELS/Compliant/EL_COM_1516S.rda")
imp=xgb.importance(model=bst)
imp
bst$evaluation_log
toc()
mat <- xgb.importance (model = bst)
xgb.plot.importance (importance_matrix = mat[51:75])
xgb.plot.gain (importance_matrix = mat[51:75])
xgb.plot.tree(model=bst)


```

Plots

```{r}

tic("Plots")
setwd("Z:/SAS Data/user/jvontela/Projects/20.IFRS9 MODELS/Compliant")
for(i in 1:nrow(imp)){
  jpeg(paste("imp_",i,"_",imp$Feature[i],"_pdp.jpeg",sep=""))
  grid.arrange(partial(bst,
                       pred.var=imp$Feature[i],
                       plot=T,
                       train=select(trainDUM[sample(nrow(trainDUM),100000),],-one_of(dropvars)),
                       type="regression")
               ,       
               partial(bst,
                       pred.var=imp$Feature[i],
                       plot=T,
                       train=select(trainDUM[which(trainDUM$CHANNELCD.ONLINE==1),],-one_of(dropvars)),
                       type="regression")
               ,
               qplot(trainDUM[,imp$Feature[i]],geom="histogram",xlab=paste(imp$Feature[i]),main=paste("All data histogram of ",
                                                                                                      imp$Feature[i]))
               ,
               qplot(trainDUM[which(trainDUM$CHANNELCD.ONLINE==1),imp$Feature[i]],geom="histogram",xlab=paste(imp$Feature[i]),
                     main=paste("Online data histogram of ",imp$Feature[i]))
               ,ncol=2)
  dev.off()}
toc()

```

```{r}
valid<-testDUM
valid$pred<-predict(bst,as.matrix(select(testDUM,-one_of(dropVars))),outputmargin=F,ntreelimit=min(bst$best_iteration,bst$niter),predcontrib=F)

RMSE(valid$pred,valid$LGD)
auc(valid$LGDrandom,valid$pred)

com_ol18<- read_sas("Z:\\SAS Data\\user\\jvontela\\Data\\com_ol18.sas7bdat")
com_ol18<-filter(com_ol18, ONLINE_CHANNEL!="STOREFRONT")

#Out of sample test
com_ol18DUM<- data_fun(com_ol18)
com_ol18$pred<-predict(bst,as.matrix(select(com_ol18DUM,-one_of(dropVars))),outputmargin=F,ntreelimit=min(bst$best_iteration,bst$niter),predcontrib=F)

RMSE(com_ol18$pred,com_ol18$LGD)
auc(com_ol18$LGD,com_ol18$pred)

library(foreign)

finaloutput2<-select(com_ol18,c("STATE","DEALNBR","MONTH_END_DATE", "LGD", "pred","BALANCE","BALANCE_AS_OF_3_22_19"))

write.foreign(finaloutput2, "Z:/SAS Data/user/jvontela/Projects/17.PD Boosted Model/ol2018_data.txt", "Z:/SAS Data/user/jvontela/Projects/17.PD Boosted Model/ol2018_data.sas",   package="SAS")

com_ol18 %>%
    group_by(MONTHENDDT) %>%
    summarise(AvgPD= mean(PD,na.rm = T), PD_SUM = sum(PD), Num = n())

com_ol18 %>%
  mutate(LOSS = pred * BALANCE ) %>%
    group_by(MONTHENDDT) %>%
    summarise(QLOSS = sum(LOSS), Num = n())



```


